# common params
run_factor: 2.0

# buttons
lower_neck_button: -1
upper_neck_button: -1
tray_button: -1
arm_joint12_button: -1
arm_joint34_button: -1
arm_joint56_button: -1
arm_joint7_button: -1
deadman_button: 0
run_button: 1
base_safety_button: -1

# axes
axis_vx: 0
axis_vy: -1
axis_vth: 1
up_down: -1 #tray--up/down; tilt--front/back, here we just name up_down
left_right: -1 #pan--left/right

# component configuration
modules: {
  base: {
    max_velocity: [1.0, 0.0, 2.0],
    max_acceleration: [1.0, 0.0, 2.0]
  },
}

